### ISSUE TITLE
Limit the 'steal' command to 10% of total up to 100k total

### ISSUE THREAD

**Issue by KRiP858** [Gelbpunkt/IdleRPG#113]
It's frustrating when someone 'steals' several 100 thousands of money from you when they use the 'steal' command.  

Can the 'steal' command be limited to 10% or 100K, whichever is greater possibly?

The economy was reset and there are a handful of players that have legitimately accumulated millions and to have 500k stolen from you is painful. Please review and thanks in advance for your consideration.

**Comment by x-Contact** [comment]
It is a luck based thing, guilds exists for a reason so that money could be stored. If you can earn money legitimately, you should be able to earn it back as well. This acts as a money sink so that the rich dont get too rich as well. It does not mean that you have to keep your money as it is, an investment on crates could be a wise idea as well.
