### ISSUE TITLE
Option for market search

### ISSUE THREAD

**Issue by Viper-ai** [Gelbpunkt/IdleRPG#116]
**Is your feature request related to a problem? Please describe.**
It's frustrating searching the market when you don't know the price range.

**Describe the solution you'd like**
An option to look for the lowest price for an item. Pokecord has this enabled with the ability to search for the lowest price available for a certain pokemon.
**Describe alternatives you've considered**
Just another price search feature to add.

**Comment by Gelbpunkt** [comment]
Have you tried using the `$shop type minstat maxprice` format yet?

**Comment by Defenestrate-flof** [comment]
We already have that feature : $[shop|market|m] [itemtype=All] [minstat=0.0] [highestprice=1000000].

Some users made tags like ?tag prices and ?tag min price but the accuracy of it is low since it's man-made and prices tend to fluctuate often. But if you check the market often, you will remember the prices regardless.
