### ISSUE TITLE
$merchall bug

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#184]
**Describe the bug**
whenever you do $merchall, it doesnt actually "merch all" of your non-equipped items.
**To Reproduce**
1. Do $merchall
2. then check your $inventory
3. 

**Expected behavior**
the command should do what it is suppose to do, $merchall of your non-equipped items

**Screenshots**
![idle#1](https://user-images.githubusercontent.com/52795906/63801650-c8487f00-c8de-11e9-9969-29cb0a1fd911.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MrDini123** [comment]
Since merchall is a very complicated operation incase if your inventory is big it takes a lot of time. Recently we added a database operation limit which could possibly result in the described behaviour. We increased it to 60 seconds which should be fine. Large inventories can still time out but in this case just redo the command.

Thanks for understanding

**Comment by Gelbpunkt** [comment]
Query timeout is now 1min, should work again
