### ISSUE TITLE
Buff $pet cuddle and $pet play

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#217]
**Is your feature request related to a problem? Please describe.**
Giving only maximum 13 points after 6 hours is too little.

**Describe the solution you'd like**
Buff the love given maximum to 30 or 20 at least.   

**Describe alternatives you've considered**
We can make cuddle and play turns into menu like $pet feed and $pet drink. 

**Additional context**
None.

**Comment by Gelbpunkt** [comment]
Your pet looses 1 joy and 3 love per 2 hours.
Counting up:
- 9 love lost in 6h
- 3 joy lost in 6h
- Every 6h, you can cuddle and play, which adds 1-12 points to the pet (means average 6)

I see the issue with love (will reduce it to 1 per 2h), but not with play

**Comment by AngelEden** [comment]
Others in my server is having this same issue. I'm seeing them do $pet cuddle and play often but still have near to nothing and only getting 1 to maybe 6 in points in it. 6h maybe to long to do these commands. Maybe drop the commands time from 6h to maybe 3h. Should help making this feature more manageable for players. Because many are quiting the Ranger class for this reason.

**Comment by Gelbpunkt** [comment]
I changed as in my comment
